alias 'add=git add'
alias 'add-all add -A'
alias 'amend=git commit --amend --no-edit'
alias 'amend-all=git commit -a --amend --no-edit'
alias 'branch=git branch'
alias 'clean=git clean -fd'
alias 'clone=git clone'
alias 'commit=git commit -m'
alias 'commit-all=git commit -am'
alias 'commit-amend-msg=git commit --amend -m'
alias 'delete=git rm'
alias 'fetch=git featch'
alias 'forget=git rm --cached'
alias 'init=git init'
alias 'log=git log --oneline --graph --decorate'
alias 'resolve=git mergetool'
alias 'modified=git diff'
alias 'pull=git pull'
alias 'push=git push'
alias 'remote=git remote'
alias 'reset=git reset'
alias 'state=git status'
alias 'tag=git tag'

